### PR TITLE
nox can be used for other projects.

### PR DESCRIPTION
**Pull request by sjmackenzie**

### CODE REVIEW

**Comment by madjar** [comment]
Hey there.

I added that check because people complained about the bad error reporting when run outside of nixpkgs.

Could you tell me on what projects you use that feature so we can find a new check that would work for all project instead of just removing it ?

Thanks !

**Comment by sjmackenzie** [comment]
Hi @madjar , so the idea is to use `github.com/fractalide/org.fractalide` which is a website to automate many of the changes in `github.com/fractalide/fractalide` . the website will run `nox` against a users clone of `fractalide/fractalide` (on the server) and give compilation feedback to users whom are developing fbp components.

**Comment by madjar** [comment]
So, I guess checking for the presence of `default.nix` would do the trick, right ?

**Comment by sjmackenzie** [comment]
I'd imagine that would do the trick!

**Comment by sjmackenzie** [comment]
ping

**Comment by madjar** [comment]
Ho, sorry, I hadn't seen you pushed a new commit. I'll merge this right away.
Can you confirm this works for you now? I'll make a new release if that's the case.

Thanks a lot!

**Pull request merged**
